apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <CLUSTER_NAME>
  region: <REGION>
  version: "<CLUSTER_VERSION>"

vpc:
  cidr: <VPC_CIDR>

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true

managedNodeGroups:
  - name: default
    instanceType: <MACHINE_TYPE>
    desiredCapacity: <DESIRED_SIZE>
    minSize: <MIN_SIZE>
    maxSize: <MAX_SIZE>
    volumeSize: <VOLUME_SIZE>