apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-waypoint-defaults
  namespace: istio-system
  labels:
    gateway.istio.io/defaults-for-class: istio-waypoint
data:
  deployment: |
    spec:
      template:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: pool-c4-standard-32
          containers:
          - name: istio-proxy
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "32"
                memory: "2Gi"
