
meld-gcp-setup:
	meld region0/Makefile gcp-setup/Makefile

meld-makefiles:
	meld region0/Makefile region1/Makefile region2/Makefile

meld-regions:
	meld region0 region1 region2

meld-failover:
	meld camunda-values.yaml region0/camunda-values-failover.yaml