# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  ingress:
    enabled: true
    className: nginx
    host: "YOUR_HOSTNAME"
    tls:
      enabled: true
      secretName: "tls-secret"
  image:
    tag: 8.1.5
    # tag: latest
    # pullPolicy: Always
  identity:
    auth:
      publicIssuerUrl: "https://YOUR_HOSTNAME/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://YOUR_HOSTNAME/operate"
      tasklist:
        redirectUrl: "https://YOUR_HOSTNAME/tasklist"
      optimize:
        redirectUrl: "https://YOUR_HOSTNAME/optimize"

operate:
  contextPath: "/operate"

tasklist:
  contextPath: "/tasklist"

optimize:
  contextPath: "/optimize"


identity:
  contextPath: "/identity"
  fullURL: "https://YOUR_HOSTNAME/identity"

  keycloak:
    #  ingress:
    #    enabled: true
    #    ingressClassName: nginx
    #    hostname: "dnslabel.location.cloudapp.azure.com"
    #    path: "/keycloak"
    #    tls: true
    #    extraHosts: []
    #    extraTls:
    #    - hosts:
    #      - dnslabel.location.cloudapp.azure.com
    #      secretName: "tls-secret"
    extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_FRONTEND_URL
        value: "https://YOUR_HOSTNAME/auth"

zeebe-gateway:
  ingress:
    enabled: true
    className: nginx
    host: "YOUR_HOSTNAME"
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"

elasticsearch:
  enabled: true
  imageTag: 7.17.3
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"






