namespace ?= camunda
release ?= camunda
chart ?= camunda/camunda-platform
chartValues ?= camunda-values.yaml

.PHONY: all
all: camunda

.PHONY: clean
clean: clean-camunda

include ../include/camunda.mk